### ISSUE TITLE
Usage as CLI tool

### ISSUE THREAD

**Issue by aidansteele** [esell/deb-simple#29]
This is a great project, thanks for making it!

Have you considered adding support for using this as a CLI tool? (Or would you accept a PR adding this mode?)

What I mean by that is I would love to be able to run `./deb-simple batch <dir full of deb files>` and have it generate all the Packages, Release, GPG-signed files, etc. I would then host the generated files on some static hosting, e.g. S3, GitHub Pages, etc.

In practice, I would run it as part of the CI pipeline for one of my projects, after `goreleaser` generates the deb files. `goreleaser` doesn't plan on doing this work itself in the near future: https://github.com/goreleaser/goreleaser/issues/912

**Comment by esell** [comment]
Hi @aidansteele, thanks for the kind words. I like the idea as a whole but I'm not sure it would fit well with this app. The main reason is that the primary goal of this app is to be the one serving up the files and to be able to handle frequent updates via REST calls. 

I feel like it might be a strange mix to have an app whose main purpose is to serve up files also be able to generate files for hosting somewhere else, especially since I initially created this to get around the issues I had hosting packages in S3 :).

While the idea sounds great (and would be a fun project), I don't think it would be a good fit for deb-simple. I do appreciate you starting the conversation though!

**Comment by aidansteele** [comment]
Thanks for the quick and thoughtful response. That reasoning makes perfect sense!
